# Generated by Django 4.1.2 on 2022-11-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('W', 'widowed'), ('D', 'divorced')], max_length=1)),
                ('alive', models.BooleanField()),
                ('death_date', models.DateField()),
            ],
        ),
    ]
